"""create users table

Revision ID: fbaf80ae131a
Revises: 
Create Date: 2025-12-01 11:14:51.916584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbaf80ae131a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("'user'::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'user'::text"))
    # ### end Alembic commands ###
